version: "3.3"
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    network_mode: host
  pokedex-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dynamodb-local
    ports:
      - "8080:8080"
    network_mode: host
