package com.pokemon.master.pokedex.gateway.database.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import java.util.List;

@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode
@With
@Getter
@Setter
@Builder
@DynamoDBTable(tableName = "MasterPokemon")
public class PokemonMasterEntity {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String idMaster;

    @DynamoDBAttribute
    @NotNull
    @NotEmpty(message = "nome não pode estar vazio")
    public String name;

    @DynamoDBAttribute
    @NotNull
    @NotEmpty(message = "genero não pode estar vazio")
    public String gender;

    @DynamoDBAttribute
    @NotNull
    @NotEmpty(message = "cidade natal não pode estar vazia")
    public String homeTown;

    @DynamoDBAttribute
    public String region;

    @DynamoDBAttribute
    public String starterPokemon;

    @DynamoDBAttribute
    public List<PokemonEntity> pokemons;


    @DynamoDBDocument
    @AllArgsConstructor
    @NoArgsConstructor
    @Getter
    @Setter
    @Builder
    public static class PokemonEntity {
        @DynamoDBAttribute(attributeName = "idPokemon")
        public Integer idPokemon;

        @DynamoDBAttribute(attributeName = "name")
        public String name;

        @DynamoDBAttribute(attributeName = "height")
        public Integer height;

        @DynamoDBAttribute(attributeName = "weight")
        public Integer weight;

        @DynamoDBAttribute(attributeName = "active")
        public boolean active;
    }

}
